question_data = [
    {"question": "Time on Computers is measured via the EPOX System.",
     "correct_answer": "False"},
    {"question": "Linus Torvalds created Linux and Git.",
     "correct_answer": "True"},
    {"question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
     "correct_answer": "True"},
    {"question": "RAM stands for Random Access Memory.", "correct_answer": "True"},
    {"question": "Linux was first created as an alternative to Windows XP.",
     "correct_answer": "False",},
    {"question": "The logo for Snapchat is a Bell.",
     "correct_answer": "False"},
    {"question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
     "correct_answer": "True"},
    {"question": "Ada Lovelace is often considered the first computer programmer.",
    "correct_answer": "True"},
    {"question": "The first IBM PC was released in 1981.",
     "correct_answer": "True"},
    {"question": "The Windows 7 operating system has six main editions.",
     "correct_answer": "True"}
    ]
